"""empty message

Revision ID: b58c39f87471
Revises: c535b3cb6e82
Create Date: 2021-03-19 15:30:39.656848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58c39f87471'
down_revision = 'c535b3cb6e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('investments_productCategoryId_fkey', 'investments', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('investments_productCategoryId_fkey', 'investments', 'product_category', ['productCategoryId'], ['id'])
    # ### end Alembic commands ###
