"""empty message

Revision ID: c535b3cb6e82
Revises: 71d54e0615dd
Create Date: 2021-03-18 12:58:40.582025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c535b3cb6e82'
down_revision = '71d54e0615dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order', 'image')
    # ### end Alembic commands ###
